### ISSUE TITLE
Only publisher and uacommander containers are running.

### ISSUE THREAD

**Issue by KingAlawaka** [digitaltwinconsortium/ManufacturingDTDLOntologies#3]
I follow the instructions as mentioned, but unfortunately all containers other than six publishers and uacommanders not starting. 
In the logs, it says,
Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:

      https://aka.ms/dotnet-download

I already installed .NET core and this is the output

dotnet.exe --list-sdks
3.1.402 [C:\Program Files\dotnet\sdk]
3.1.416 [C:\Program Files\dotnet\sdk]

Any thoughts on what went wrong?

![image](https://user-images.githubusercontent.com/13180028/155852343-b6abfb09-f44e-4d45-89c3-e37ac7ea00eb.png)

Thanks in advance,
Pasindu

**Comment by KingAlawaka** [comment]
I realized the issue was, BuildOutput was copied to the /app folder in the container, but .dll files are not in the right place. Inside the BuildAndRun.cmd file .dlls are trying to access directly inside the /app folder. But the correct folder is /app/bin/ so as a quick fix I manually copy-paste all the .dll files in the bin folder to the parent folder BuildOutput. However, it fixes the old issue but now I am facing a new issue 

![image](https://user-images.githubusercontent.com/13180028/155880525-c03ad24b-33e4-4518-878f-1e724aaaae16.png)

Since it's not working, I decided to change the paths in the BuildAndRun.cmd appropriately to access the .dlls. without moving them manually. 
I change /app/Station.dll to /app/bin/Station.dll
However, now I'm getting an error like this.

![image](https://user-images.githubusercontent.com/13180028/155881071-873d75f7-08d6-4b93-8916-804691691895.png)


Any thoughts about this?

**Comment by barnstee** [comment]
Let me try to repro on a clean machine.

**Comment by barnstee** [comment]
Can you send me the output of the dotnet --info command, please? Also, the build of the container should create a .\BuildOutput directory with the DLLs in there, not in /bin. ./Buildoutput is then mapped to /app within the container. Did you run the script from the .\FactorySimulation folder?

**Comment by KingAlawaka** [comment]
Sorry for the late reply.

This is the output of dotnet --info command
![image](https://user-images.githubusercontent.com/13180028/156853277-642da2ca-718a-4260-bdae-3e02e723db4e.png)

Yes, I run the script inside the  .\FactorySimulation. 
When building the project it is not building the DLLs inside the BuildOutput folder. It is created inside ./Buildoutput/bin
Because of this, I manually move the DLLs from the bin folder but still, it's not working.

Thank you very much for your support

**Comment by barnstee** [comment]
Thanks for the detailed steps. I managed to reproduce it and fixed it. Please try it out.

**Comment by barnstee** [comment]
Fixed with checkin https://github.com/digitaltwinconsortium/ManufacturingDTDLOntologies/commit/86f14d399f09687f147e1180e1585f39386ba82c

**Comment by KingAlawaka** [comment]
I will check this and let you know about it. 
Thanks again for your support

**Comment by KingAlawaka** [comment]
I am still getting this error. Any thoughts?
![image](https://user-images.githubusercontent.com/13180028/157142864-29ab0666-1b24-4dc4-a170-1d030e91466e.png)

When I stop the running containers, I see these containers are not attached to the network error. I am not sure whether it's related to this issue or because containers have not started correctly. Hope this helps too.
![image](https://user-images.githubusercontent.com/13180028/157143742-5fb40f79-3b1f-4550-8a44-c6a81a956c69.png)

**Comment by barnstee** [comment]
The container not connected to network is simply a follow-on issue since they containers did not start. The assembly not found error appears to be a known issue with dotnetcore 2.1, see here: https://stackoverflow.com/questions/52028310/could-not-load-file-or-assembly-microsoft-aspnetcore-connections-abstractions. Upgrading to 2.1.5 appears to be fixing it. Can you try?

**Comment by KingAlawaka** [comment]
Can you please explain to me how can I do that? 
because in the .csproj file .NetCore is 3.1.0
![image](https://user-images.githubusercontent.com/13180028/157348544-13156c5d-f69e-4caa-9525-4e2d8df727ec.png)

Thanks in advance

**Comment by barnstee** [comment]
Sorry man, I just realized that you had 3.1 already installed. I had another look and it turns out there was a conflict between the assemblies generated from the Azure Function "Pressure Relief" and the MES/Station project, even though they all use DotNetCore 3.1. I have moved the Pressure Relief project into its own solution (and folder) and now it is working for me. Please sync and try again. Sorry for taking so long to fix this.

**Comment by KingAlawaka** [comment]
Thank you very much for your kind support. Now it's working. 
The moving Pressure Relief function did the trick. 
I also sent you an email. 
Thanks again
